# Generated by Django 6.0.2 on 2026-04-14 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litreview', '0002_alter_ticket_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('ticket', 'user'), name='unique_review_per_user_per_ticket'),
        ),
    ]
